import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#743400",
        "surface-bright": "#fef7ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#5b00c5",
        "on-primary": "#ffffff",
        "primary-container": "#6d28d9",
        "on-secondary-fixed": "#0b1c30",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdbc8",
        "surface-container-high": "#ede5f3",
        "on-secondary-fixed-variant": "#38485d",
        "secondary-fixed": "#d3e4fe",
        "surface-tint": "#7331df",
        "on-secondary-container": "#54647a",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f6eefc",
        "surface-container-low": "#f9f1ff",
        "inverse-surface": "#332f39",
        "on-primary-fixed": "#250059",
        "surface-container-highest": "#e8e0ee",
        "on-background": "#1d1a24",
        "on-surface": "#1d1a24",
        "primary-fixed-dim": "#d3bbff",
        "inverse-primary": "#d3bbff",
        "background": "#fef7ff",
        "surface-variant": "#e8e0ee",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb68b",
        "on-surface-variant": "#4a4455",
        "on-tertiary-fixed": "#321300",
        "surface": "#fef7ff",
        "primary-fixed": "#ebddff",
        "on-tertiary-container": "#ffc19e",
        "on-primary-container": "#dac5ff",
        "outline-variant": "#ccc3d7",
        "surface-dim": "#dfd7e5",
        "tertiary": "#6b3000",
        "tertiary-container": "#8f4200",
        "outline": "#7b7486",
        "secondary-fixed-dim": "#b7c8e1",
        "primary": "#5300b7",
        "surface-container": "#f3ebf9",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "secondary": "#505f76",
        "secondary-container": "#d0e1fb",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "8px",
        lg: "24px",
        xs: "4px",
        xl: "48px",
        gutter: "20px",
        "container-margin": "32px",
        md: "16px",
        unit: "4px",
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-mono": ["13px", { lineHeight: "1.2", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
